#==========================================================
#
#   
#   ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
#   ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
#   ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
#   ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
#   ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
#   ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     
# 
#   Please see https://starship.rs/config/ for a complete reference!
#
#==========================================================

add_newline = true


format = """
 [┌───=](bold blue)[\\[$username@$hostname $directory\\]](bold) $git_branch
 [└─>](bold blue) [\\$](bold) """

[hostname]
ssh_only = false
format =  "$hostname"
disabled = false

[username]
format = "$user"
disabled = false
show_always = true
